-- Verification tables (AG-05, M1): decisions (append-only), Rejection_Log (ТЗ §10 #6), Dispute_Log (#7),
-- Dataset_Items (#15, GOLD drafts), idempotency replay store, usability ui_events; invariants I1, I2, I3, I4 of
-- 05 §3.20 as constraints and triggers. DDL generated by drizzle-kit from verification.schema.ts; constraints,
-- triggers and comments below the marker are hand-written. Apply after 0003 (AG-00 adds the journal entry).
CREATE TABLE "dataset_items" (
	"id" uuid PRIMARY KEY NOT NULL,
	"evidence_group_id" varchar(96),
	"gold_label" varchar(16) NOT NULL,
	"expert_id" uuid NOT NULL,
	"reason_code" varchar(48),
	"dataset_version" text,
	"split" varchar(16) NOT NULL,
	"object_group_id" varchar(64),
	"status" varchar(24) NOT NULL,
	"object_id" varchar(64) NOT NULL,
	"process_id" uuid NOT NULL,
	"protocol_id" uuid NOT NULL,
	"protocol_version" integer NOT NULL,
	"check_id" bigint NOT NULL,
	"finding_id" varchar(96) NOT NULL,
	"decision_id" uuid NOT NULL,
	"source_type" varchar(16) NOT NULL,
	"gold_record" jsonb NOT NULL,
	"evidence_card" jsonb NOT NULL,
	"versions" jsonb NOT NULL,
	"training_eligible" boolean NOT NULL,
	"decided_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "dataset_items_protocol_finding_uq" UNIQUE("protocol_id","finding_id")
);
--> statement-breakpoint
CREATE TABLE "dispute_log" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"violation_id" bigint NOT NULL,
	"decision_id" uuid NOT NULL,
	"process_id" uuid NOT NULL,
	"finding_id" varchar(96) NOT NULL,
	"rejection_reason" varchar(48) NOT NULL,
	"inspector_comment" text NOT NULL,
	"ai_comment" text NOT NULL,
	"ai_rule_ids" text[] NOT NULL,
	"ai_evidence" jsonb,
	"resolution_status" varchar(24) DEFAULT 'OPEN' NOT NULL,
	"resolved_by" uuid,
	"resolution_comment" text,
	"resolution_decision_id" uuid,
	"row_version" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"resolved_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "rejection_log" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"violation_id" bigint NOT NULL,
	"decision_id" uuid NOT NULL,
	"process_id" uuid NOT NULL,
	"object_id" varchar(64) NOT NULL,
	"finding_id" varchar(96) NOT NULL,
	"param_code" varchar(32) NOT NULL,
	"rejection_reason" varchar(48) NOT NULL,
	"reason_comment" text NOT NULL,
	"corrected_value" jsonb,
	"ai_verdict" varchar(16) NOT NULL,
	"ai_confidence" numeric(4, 3),
	"ai_rule_ids" text[] DEFAULT '{}'::text[] NOT NULL,
	"ai_comment" text,
	"suggested_fix" text,
	"retraining_status" varchar(24) NOT NULL,
	"curator_flag" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ui_events" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"session_id" uuid,
	"user_id" uuid NOT NULL,
	"process_id" uuid,
	"finding_id" varchar(96),
	"type" varchar(32) NOT NULL,
	"target" varchar(64),
	"input" varchar(16),
	"ts_client" timestamp with time zone NOT NULL,
	"ts_server" timestamp with time zone DEFAULT now() NOT NULL,
	"payload" jsonb
);
--> statement-breakpoint
CREATE TABLE "verification_decisions" (
	"id" uuid PRIMARY KEY NOT NULL,
	"process_id" uuid NOT NULL,
	"check_id" bigint NOT NULL,
	"finding_id" varchar(96) NOT NULL,
	"finding_group_id" varchar(96),
	"object_id" varchar(64) NOT NULL,
	"run_id" uuid,
	"protocol_id" uuid,
	"protocol_version" integer,
	"decision" varchar(32) NOT NULL,
	"effective_status" varchar(32) NOT NULL,
	"reason_code" varchar(48),
	"basis_code" varchar(48),
	"clarify_code" varchar(48),
	"comment" text NOT NULL,
	"comment_source" varchar(16) NOT NULL,
	"system_comment" text,
	"approved_change_ref" text,
	"approved_change_file_id" varchar(512),
	"approved_change_page" integer,
	"corrected_value" jsonb,
	"correct_file_id" varchar(512),
	"correct_locus" text,
	"duplicate_of" varchar(96),
	"na_basis" text,
	"justification" text,
	"planned_action" varchar(32),
	"ai_verdict" varchar(16),
	"ai_confidence" numeric(4, 3),
	"ai_rule_ids" text[] DEFAULT '{}'::text[] NOT NULL,
	"ai_comment" text,
	"gold_effect" varchar(16) NOT NULL,
	"seen_fingerprint" char(64) NOT NULL,
	"evidence_snapshot" jsonb NOT NULL,
	"supersedes_decision_id" uuid,
	"override_of_decision_id" uuid,
	"resolves_dispute_id" bigint,
	"user_id" uuid NOT NULL,
	"user_role" varchar(128) NOT NULL,
	"user_login" varchar(64),
	"ip_address" "inet",
	"user_agent" text,
	"request_id" varchar(128),
	"idempotency_key" uuid NOT NULL,
	"client_metrics" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "verification_decisions_user_key_uq" UNIQUE("user_id","idempotency_key")
);
--> statement-breakpoint
CREATE TABLE "verification_idempotency" (
	"user_id" uuid NOT NULL,
	"idempotency_key" uuid NOT NULL,
	"operation" varchar(64) NOT NULL,
	"request_sha256" char(64) NOT NULL,
	"status_code" integer NOT NULL,
	"response_body" jsonb NOT NULL,
	"etag" varchar(32),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "verification_idempotency_user_id_idempotency_key_pk" PRIMARY KEY("user_id","idempotency_key")
);
--> statement-breakpoint
ALTER TABLE "dataset_items" ADD CONSTRAINT "dataset_items_protocol_id_protocols_id_fk" FOREIGN KEY ("protocol_id") REFERENCES "public"."protocols"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "dataset_items" ADD CONSTRAINT "dataset_items_decision_id_verification_decisions_id_fk" FOREIGN KEY ("decision_id") REFERENCES "public"."verification_decisions"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "dispute_log" ADD CONSTRAINT "dispute_log_violation_id_checks_id_fk" FOREIGN KEY ("violation_id") REFERENCES "public"."checks"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "dispute_log" ADD CONSTRAINT "dispute_log_decision_id_verification_decisions_id_fk" FOREIGN KEY ("decision_id") REFERENCES "public"."verification_decisions"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "rejection_log" ADD CONSTRAINT "rejection_log_violation_id_checks_id_fk" FOREIGN KEY ("violation_id") REFERENCES "public"."checks"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "rejection_log" ADD CONSTRAINT "rejection_log_decision_id_verification_decisions_id_fk" FOREIGN KEY ("decision_id") REFERENCES "public"."verification_decisions"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "verification_decisions" ADD CONSTRAINT "verification_decisions_process_id_processes_id_fk" FOREIGN KEY ("process_id") REFERENCES "public"."processes"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "verification_decisions" ADD CONSTRAINT "verification_decisions_check_id_checks_id_fk" FOREIGN KEY ("check_id") REFERENCES "public"."checks"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "dataset_items_status_idx" ON "dataset_items" USING btree ("status","split");
--> statement-breakpoint
CREATE INDEX "dataset_items_object_idx" ON "dataset_items" USING btree ("object_id","created_at");
--> statement-breakpoint
CREATE INDEX "dispute_log_process_idx" ON "dispute_log" USING btree ("process_id","resolution_status");
--> statement-breakpoint
CREATE INDEX "dispute_log_violation_idx" ON "dispute_log" USING btree ("violation_id");
--> statement-breakpoint
CREATE INDEX "rejection_log_process_idx" ON "rejection_log" USING btree ("process_id","created_at");
--> statement-breakpoint
CREATE INDEX "rejection_log_reason_idx" ON "rejection_log" USING btree ("rejection_reason");
--> statement-breakpoint
CREATE INDEX "ui_events_process_idx" ON "ui_events" USING btree ("process_id","ts_client");
--> statement-breakpoint
CREATE INDEX "ui_events_session_idx" ON "ui_events" USING btree ("session_id","ts_client");
--> statement-breakpoint
CREATE INDEX "verification_decisions_check_idx" ON "verification_decisions" USING btree ("check_id","created_at");
--> statement-breakpoint
CREATE INDEX "verification_decisions_process_idx" ON "verification_decisions" USING btree ("process_id","created_at");
--> statement-breakpoint
-- ── hand-written: owner tags ──
COMMENT ON TABLE "verification_decisions" IS 'owner=B05 (AG-05); one row per inspector action on one atomic finding; append-only (05 §3.14)';--> statement-breakpoint
COMMENT ON TABLE "rejection_log" IS 'owner=B05 (AG-05); ТЗ §10 table 6 (violation_id = checks.id); AI verdict per rejection';--> statement-breakpoint
COMMENT ON TABLE "dispute_log" IS 'owner=B05 (AG-05); ТЗ §10 table 7; the AI disagrees with a rejection (§9.4 sample 2)';--> statement-breakpoint
COMMENT ON TABLE "dataset_items" IS 'owner=B06→AG-05 (lean M4); ТЗ §10 table 15; GOLD drafts from final decisions, never exported to a submission';--> statement-breakpoint
COMMENT ON TABLE "verification_idempotency" IS 'owner=B05 (AG-05); Idempotency-Key replay store of verification writes';--> statement-breakpoint
COMMENT ON TABLE "ui_events" IS 'owner=B05 (AG-05); usability telemetry (VER-68), pseudonymous';--> statement-breakpoint

-- ── hand-written: vocabularies (enums.yaml) as CHECK constraints; no PARTIALLY_CONFIRMED anywhere (I2) ──
ALTER TABLE "verification_decisions" ADD CONSTRAINT "verification_decisions_decision_chk"
  CHECK ("decision" IN ('CONFIRMED_VIOLATION', 'NEGATIVE_VERIFIED', 'CLARIFICATION_REQUIRED', 'REVERT_TO_PENDING'));--> statement-breakpoint
ALTER TABLE "verification_decisions" ADD CONSTRAINT "verification_decisions_effective_status_chk"
  CHECK ("effective_status" IN ('PENDING', 'CONFIRMED_VIOLATION', 'NEGATIVE_VERIFIED', 'CLARIFICATION_REQUIRED'));--> statement-breakpoint
ALTER TABLE "verification_decisions" ADD CONSTRAINT "verification_decisions_comment_chk" CHECK (length(btrim("comment")) > 0);--> statement-breakpoint
ALTER TABLE "verification_decisions" ADD CONSTRAINT "verification_decisions_reject_reason_chk"
  CHECK ("decision" <> 'NEGATIVE_VERIFIED' OR "reason_code" IS NOT NULL);--> statement-breakpoint
ALTER TABLE "verification_decisions" ADD CONSTRAINT "verification_decisions_gold_effect_chk"
  CHECK ("gold_effect" IN ('POSITIVE_DRAFT', 'NEGATIVE_DRAFT', 'WITHDRAW', 'NONE'));--> statement-breakpoint
ALTER TABLE "dispute_log" ADD CONSTRAINT "dispute_log_resolution_status_chk"
  CHECK ("resolution_status" IN ('OPEN', 'INSPECTOR_UPHELD', 'AI_UPHELD', 'KEPT_CLARIFICATION', 'ESCALATED', 'WITHDRAWN'));--> statement-breakpoint
ALTER TABLE "rejection_log" ADD CONSTRAINT "rejection_log_ai_verdict_chk" CHECK ("ai_verdict" IN ('AGREE', 'UNCERTAIN', 'DISAGREE'));--> statement-breakpoint
ALTER TABLE "dataset_items" ADD CONSTRAINT "dataset_items_gold_label_chk" CHECK ("gold_label" IN ('POSITIVE', 'NEGATIVE'));--> statement-breakpoint
ALTER TABLE "checks" ADD CONSTRAINT "checks_inspector_status_chk"
  CHECK ("inspector_status" IS NULL OR "inspector_status" IN ('PENDING', 'CONFIRMED_VIOLATION', 'NEGATIVE_VERIFIED', 'CLARIFICATION_REQUIRED'));--> statement-breakpoint
-- I1: CONFIRMED_VIOLATION exists only through an inspector decision (no import or model path can set it).
ALTER TABLE "checks" ADD CONSTRAINT "checks_confirmed_by_inspector_chk"
  CHECK (("finding_status" IS DISTINCT FROM 'CONFIRMED_VIOLATION' AND "inspector_status" IS DISTINCT FROM 'CONFIRMED_VIOLATION')
         OR "decided_by" = 'INSPECTOR');--> statement-breakpoint
ALTER TABLE "checks" ADD CONSTRAINT "checks_current_decision_fk" FOREIGN KEY ("current_decision_id")
  REFERENCES "public"."verification_decisions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint

-- ── hand-written: I3 decisions are append-only ──
CREATE OR REPLACE FUNCTION verification_decisions_block_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'VERIFICATION_DECISIONS_APPEND_ONLY: % on verification_decisions is not allowed', TG_OP
    USING ERRCODE = 'insufficient_privilege';
END;
$$;--> statement-breakpoint
-- Row-level only: TRUNCATE … CASCADE of processes stays possible for maintenance of test databases.
CREATE TRIGGER verification_decisions_block_update_delete
  BEFORE UPDATE OR DELETE ON "verification_decisions"
  FOR EACH ROW EXECUTE FUNCTION verification_decisions_block_mutation();--> statement-breakpoint

-- ── hand-written: I4 nothing changes after finalization (defence in depth behind the API's 423) ──
CREATE OR REPLACE FUNCTION verification_block_when_finalized() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  st varchar;
BEGIN
  SELECT "status" INTO st FROM "processes" WHERE "id" = NEW."process_id";
  IF st = 'FINALIZED' THEN
    RAISE EXCEPTION 'PROTOCOL_FINALIZED: process % is finalized; un-finalize it first', NEW."process_id"
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$;--> statement-breakpoint
CREATE TRIGGER verification_decisions_block_finalized
  BEFORE INSERT ON "verification_decisions"
  FOR EACH ROW EXECUTE FUNCTION verification_block_when_finalized();--> statement-breakpoint
CREATE TRIGGER dispute_log_block_finalized
  BEFORE INSERT OR UPDATE ON "dispute_log"
  FOR EACH ROW EXECUTE FUNCTION verification_block_when_finalized();--> statement-breakpoint
CREATE TRIGGER rejection_log_block_finalized
  BEFORE INSERT ON "rejection_log"
  FOR EACH ROW EXECUTE FUNCTION verification_block_when_finalized();--> statement-breakpoint
-- Inspector columns of checks only: the import rewrites machine columns and refuses finalized processes itself.
CREATE TRIGGER checks_inspector_block_finalized
  BEFORE UPDATE ON "checks"
  FOR EACH ROW
  WHEN (OLD."inspector_status" IS DISTINCT FROM NEW."inspector_status"
        OR OLD."decided_by" IS DISTINCT FROM NEW."decided_by"
        OR OLD."decided_user_id" IS DISTINCT FROM NEW."decided_user_id"
        OR OLD."decision_reason_code" IS DISTINCT FROM NEW."decision_reason_code"
        OR OLD."decision_basis_code" IS DISTINCT FROM NEW."decision_basis_code"
        OR OLD."decision_comment" IS DISTINCT FROM NEW."decision_comment"
        OR OLD."current_decision_id" IS DISTINCT FROM NEW."current_decision_id")
  EXECUTE FUNCTION verification_block_when_finalized();--> statement-breakpoint
-- Rejection_Log and Dispute_Log rows are never deleted (legal record, 05 §3.14 retention).
CREATE OR REPLACE FUNCTION verification_logs_block_delete() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'VERIFICATION_LOG_APPEND_ONLY: DELETE on % is not allowed', TG_TABLE_NAME
    USING ERRCODE = 'insufficient_privilege';
END;
$$;--> statement-breakpoint
CREATE TRIGGER rejection_log_block_delete
  BEFORE DELETE ON "rejection_log"
  FOR EACH ROW EXECUTE FUNCTION verification_logs_block_delete();--> statement-breakpoint
CREATE TRIGGER dispute_log_block_delete
  BEFORE DELETE ON "dispute_log"
  FOR EACH ROW EXECUTE FUNCTION verification_logs_block_delete();
