/**
 * Drizzle schema: the M0 subset of the canonical data model (docs/analysis/90 §3.3, 97 §2.8).
 *
 * - `runs`    (90 §3.3.4, owner B00): here, one row per imported `inspector-batch` run directory.
 * - `objects` (ТЗ table 3, owner B01): ТЗ key fields + extensions used by the dashboard.
 * - `files`   (ТЗ table 4, owner B01): ТЗ key fields + the 97 §2.8 manifest fields and `local_status`.
 *
 * Column values that are enums hold codes of packages/contracts/enums.yaml (noted per column).
 * Migrations: `pnpm --filter @inspector/api db:generate` → drizzle/*.sql; apply with `db:migrate`.
 */
import { sql } from 'drizzle-orm';
import {
  bigint,
  boolean,
  char,
  date,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';

const tstz = (name: string) => timestamp(name, { withTimezone: true, mode: 'date' });

export const runs = pgTable(
  'runs',
  {
    /** UUID v7 (90 §3.3.2), generated by the API. */
    id: uuid('id').primaryKey(),
    /** `run_id` of run_manifest.json; one import record per batch run. */
    batchRunId: varchar('batch_run_id', { length: 128 }).notNull().unique(),
    /** Web-mode process; NULL for batch imports (inspector-batch has no process). */
    processId: uuid('process_id'),
    /** RunMode; NULL for batch imports. */
    mode: varchar('mode', { length: 16 }),
    producer: varchar('producer', { length: 32 }).notNull(),
    command: text('command'),
    /** RunStatus */
    status: varchar('status', { length: 16 }).notNull(),
    configHash: char('config_hash', { length: 64 }).notNull(),
    freezeTag: text('freeze_tag'),
    pipelineVersion: text('pipeline_version').notNull(),
    matrixVersion: text('matrix_version'),
    datasetVersion: text('dataset_version'),
    modelVersion: text('model_version'),
    engineVersions: jsonb('engine_versions'),
    /** The whole `versions` block (common.schema.json#/$defs/Versions). */
    versions: jsonb('versions').notNull(),
    /** `inputs` block: sha256 of the organizer inputs. */
    inputs: jsonb('inputs').notNull(),
    host: jsonb('host'),
    /** Absolute path of the imported run_manifest.json (90 `runs.manifest_ref`). */
    manifestRef: text('manifest_ref').notNull(),
    manifestSha256: char('manifest_sha256', { length: 64 }).notNull(),
    /** The imported RunManifest as is (provenance; artifacts are never read for hidden objects). */
    manifest: jsonb('manifest').notNull(),
    timings: jsonb('timings'),
    /** ProblemItem[] raised while importing. */
    importWarnings: jsonb('import_warnings').notNull().default(sql`'[]'::jsonb`),
    objectsCount: integer('objects_count').notNull(),
    filesCount: integer('files_count').notNull(),
    startedAt: tstz('started_at').notNull(),
    finishedAt: tstz('finished_at'),
    importedAt: tstz('imported_at').notNull().defaultNow(),
    /** «Архивировать»: hidden from lists and from the protocol lookup (fixture / stale runs). */
    archivedAt: tstz('archived_at'),
    updatedAt: tstz('updated_at').notNull().defaultNow(),
  },
  (t) => [index('runs_imported_at_idx').on(t.importedAt)],
);

export const objects = pgTable('objects', {
  /** object_id (registry / manifest mnemonic). */
  id: varchar('id', { length: 64 }).primaryKey(),
  // ТЗ key fields (§10.3). Not in the organizer package; filled later by the objects API.
  name: text('name'),
  address: text('address'),
  customer: text('customer'),
  contractor: text('contractor'),
  permitNumber: text('permit_number'),
  // Extensions (90 §3.3.3, 97 §2.8).
  /** ManifestSplit */
  split: varchar('split', { length: 16 }),
  objectGroupId: varchar('object_group_id', { length: 64 }),
  inputManifestHash: char('input_manifest_hash', { length: 64 }),
  /** LoadScenario */
  scenario: varchar('scenario', { length: 24 }),
  /** IndicatorColor (computed by the dashboard module; NONE until a protocol exists). */
  indicatorColor: varchar('indicator_color', { length: 8 }).notNull().default('NONE'),
  indicatorReasons: jsonb('indicator_reasons'),
  indicatorUpdatedAt: tstz('indicator_updated_at'),
  lastRunId: uuid('last_run_id').references(() => runs.id),
  /** «Архивировать»: hidden from lists and the dashboard by default. */
  archivedAt: tstz('archived_at'),
  createdAt: tstz('created_at').notNull().defaultNow(),
  updatedAt: tstz('updated_at').notNull().defaultNow(),
});

export const files = pgTable(
  'files',
  {
    /** file_id (contract FileId, ≤ 512: manifest ids today, archive members later). */
    id: varchar('id', { length: 512 }).primaryKey(),
    objectId: varchar('object_id', { length: 64 })
      .notNull()
      .references(() => objects.id),
    // ТЗ key fields (§10.4). Resolved by later stages (AG-01/AG-02B); NULL after inventory.
    /** DocStage resolved per file (manifest RD_ID_MIXED/UNKNOWN resolve later). */
    docStage: varchar('doc_stage', { length: 8 }),
    discipline: varchar('discipline', { length: 32 }),
    documentCode: text('document_code'),
    revision: text('revision'),
    /** ApprovalStatus */
    approvalStatus: varchar('approval_status', { length: 24 }),
    approvalDate: date('approval_date'),
    predecessorId: varchar('predecessor_id', { length: 512 }),
    /** SHA-256 of the file bytes (= manifest/API `sha256`, 90 §3.3.6). Immutable per file_id. */
    fileHash: char('file_hash', { length: 64 }).notNull(),
    /** Storage key: the manifest relative_path (base 01_ДОКУМЕНТАЦИЯ). */
    filePath: text('file_path'),
    uploadedAt: tstz('uploaded_at').notNull().defaultNow(),
    // Extensions.
    fileName: text('file_name').notNull(),
    ext: varchar('ext', { length: 16 }),
    sizeBytes: bigint('size_bytes', { mode: 'number' }),
    // 97 §2.8 manifest fields.
    /** ManifestStage (kept raw next to the resolved doc_stage). */
    manifestStage: varchar('manifest_stage', { length: 16 }).notNull(),
    /** ManifestSection (open vocabulary). */
    manifestSection: varchar('manifest_section', { length: 32 }),
    /** DatasetRole (open vocabulary). */
    datasetRole: varchar('dataset_role', { length: 32 }),
    /** ManifestSplit */
    split: varchar('split', { length: 16 }),
    duplicateGroup: text('duplicate_group'),
    /** AnnotationStatus (open vocabulary). */
    annotationStatus: varchar('annotation_status', { length: 32 }),
    pdfPages: integer('pdf_pages'),
    /** LocalFileStatus — never MISSING_DOCUMENT (97 §2.12). */
    localStatus: varchar('local_status', { length: 16 }).notNull(),
    sha256Verified: boolean('sha256_verified'),
    lastRunId: uuid('last_run_id').references(() => runs.id),
    createdAt: tstz('created_at').notNull().defaultNow(),
    updatedAt: tstz('updated_at').notNull().defaultNow(),
  },
  (t) => [index('files_object_stage_idx').on(t.objectId, t.manifestStage), index('files_file_hash_idx').on(t.fileHash)],
);

export type RunRow = typeof runs.$inferSelect;
export type NewRunRow = typeof runs.$inferInsert;
export type ObjectRow = typeof objects.$inferSelect;
export type NewObjectRow = typeof objects.$inferInsert;
export type FileRow = typeof files.$inferSelect;
export type NewFileRow = typeof files.$inferInsert;
